import {
   Announcement,
   Beaker,
   Bio,
   Blossom,
   BookOpen,
   BookClosed,
   Branch,
   Calendar,
   Chat,
   Check,
   Clock,
   Computer,
   DPCTree,
   EnhanceDiversity,
   GraduationCap,
   Graph,
   Growth,
   Institution,
   LightbulbIdea,
   Location,
   News,
   Notes,
   People,
   Person,
   PersonStar,
   Phone,
   Ruler,
} from 'src/assets/icons/primary';

import {
   OrangeBranch,
   OrangeLeafGradient,
   OrangeLeafOutline,
   OrangeLeaf,
   OrangeLeavesGradient,
   OrangeLeavesOutline,
   OrangeLeaves,
   BlueBranch,
   BlueLeafGradient,
   BlueLeafOutline,
   BlueLeaf,
   BlueLeavesGradient,
   BlueLeavesOutline,
   BlueLeaves,
   GreenBranch,
   GreenLeafGradient,
   GreenLeafOutline,
   GreenLeaf,
   GreenLeavesGradient,
   GreenLeavesOutline,
   GreenLeaves,
   YellowBranch,
   YellowLeafGradient,
   YellowLeafOutline,
   YellowLeaf,
   YellowLeavesGradient,
   YellowLeavesOutline,
   YellowLeaves,
   DPCBranchTree,
} from 'src/assets/icons/tree';

export const iconMap: Record<string, string> = {
   Announcement: Announcement.src,
   Beaker: Beaker.src,
   Bio: Bio.src,
   Blossom: Blossom.src,
   'Book-Open': BookOpen.src,
   'Book-Closed': BookClosed.src,
   Branch: Branch.src,
   Calendar: Calendar.src,
   Chat: Chat.src,
   Check: Check.src,
   Clock: Clock.src,
   Computer: Computer.src,
   DPCTree: DPCTree.src,
   'Enhance-Diversity': EnhanceDiversity.src,
   'Graduation-Cap': GraduationCap.src,
   Graph: Graph.src,
   Growth: Growth.src,
   Institution: Institution.src,
   'Lightbulb-Idea': LightbulbIdea.src,
   Location: Location.src,
   News: News.src,
   Notes: Notes.src,
   People: People.src,
   Person: Person.src,
   'Person-Star': PersonStar.src,
   Phone: Phone.src,
   Ruler: Ruler.src,
   'DPC-Tree': DPCBranchTree.src,
   'BUILD-Orange-Branch': OrangeBranch.src,
   'BUILD-Orange-Leaf-Gradient': OrangeLeafGradient.src,
   'BUILD-Orange-Leaf-Outline': OrangeLeafOutline.src,
   'BUILD-Orange-Leaf': OrangeLeaf.src,
   'BUILD-Orange-Leaves-Gradient': OrangeLeavesGradient.src,
   'BUILD-Orange-Leaves-Outline': OrangeLeavesOutline.src,
   'BUILD-Orange-Leaves': OrangeLeaves.src,
   'CEC-Blue-Branch': BlueBranch.src,
   'CEC-Blue-Leaf-Gradient': BlueLeafGradient.src,
   'CEC-Blue-Leaf-Outline': BlueLeafOutline.src,
   'CEC-Blue-Leaf': BlueLeaf.src,
   'CEC-Blue-Leaves-Gradient': BlueLeavesGradient.src,
   'CEC-Blue-Leaves-Outline': BlueLeavesOutline.src,
   'CEC-Blue-Leaves': BlueLeaves.src,
   'NIH-Green-Branch': GreenBranch.src,
   'NIH-Green-Leaf-Gradient': GreenLeafGradient.src,
   'NIH-Green-Leaf-Outline': GreenLeafOutline.src,
   'NIH-Green-Leaf': GreenLeaf.src,
   'NIH-Green-Leaves-Gradient': GreenLeavesGradient.src,
   'NIH-Green-Leaves-Outline': GreenLeavesOutline.src,
   'NIH-Green-Leaves': GreenLeaves.src,
   'NRMN-Yellow-Branch': YellowBranch.src,
   'NRMN-Yellow-Leaf-Gradient': YellowLeafGradient.src,
   'NRMN-Yellow-Leaf-Outline': YellowLeafOutline.src,
   'NRMN-Yellow-Leaf': YellowLeaf.src,
   'NRMN-Yellow-Leaves-Gradient': YellowLeavesGradient.src,
   'NRMN-Yellow-Leaves-Outline': YellowLeavesOutline.src,
   'NRMN-Yellow-Leaves': YellowLeaves.src,
};
