export const types = ['dpc', 'font-awesome-solid', 'font-awesome-regular', 'font-awesome-brands'];

export const typeMap = {
   dpc: 'dpc',
   'font-awesome-solid': 'font-awesome-solid',
   'font-awesome-regular': 'font-awesome-regular',
   'font-awesome-brands': 'font-awesome-brands',
};

export const dpcIcons = [
   'Announcement',
   'Beaker',
   'Bio',
   'Blossom',
   'Book-Open',
   'Book-Closed',
   'Branch',
   'Calendar',
   'Chat',
   'Check',
   'Clock',
   'Computer',
   'DPCTree',
   'Enhance-Diversity',
   'Graduation-Cap',
   'Graph',
   'Growth',
   'Institution',
   'Lightbulb-Idea',
   'Location',
   'News',
   'Notes',
   'People',
   'Person',
   'Person-Star',
   'Phone',
   'Ruler',
   'DPC-Tree',
   'BUILD-Orange-Branch',
   'BUILD-Orange-Leaf-Gradient',
   'BUILD-Orange-Leaf-Outline',
   'BUILD-Orange-Leaf',
   'BUILD-Orange-Leaves-Gradient',
   'BUILD-Orange-Leaves-Outline',
   'BUILD-Orange-Leaves',
   'CEC-Blue-Branch',
   'CEC-Blue-Leaf-Gradient',
   'CEC-Blue-Leaf-Outline',
   'CEC-Blue-Leaf',
   'CEC-Blue-Leaves-Gradient',
   'CEC-Blue-Leaves-Outline',
   'CEC-Blue-Leaves',
   'NIH-Green-Branch',
   'NIH-Green-Leaf-Gradient',
   'NIH-Green-Leaf-Outline',
   'NIH-Green-Leaf',
   'NIH-Green-Leaves-Gradient',
   'NIH-Green-Leaves-Outline',
   'NIH-Green-Leaves',
   'NRMN-Yellow-Branch',
   'NRMN-Yellow-Leaf-Gradient',
   'NRMN-Yellow-Leaf-Outline',
   'NRMN-Yellow-Leaf',
   'NRMN-Yellow-Leaves-Gradient',
   'NRMN-Yellow-Leaves-Outline',
   'NRMN-Yellow-Leaves',
];

export const dpcIconsMap = {
   Announcement: 'Announcement',
   Beaker: 'Beaker',
   Bio: 'Bio',
   Blossom: 'Blossom',
   'Book-Open': 'Book-Open',
   'Book-Closed': 'Book-Closed',
   Branch: 'Branch',
   Calendar: 'Calendar',
   Chat: 'Chat',
   Check: 'Check',
   Clock: 'Clock',
   Computer: 'Computer',
   DPCTree: 'DPCTree',
   'Enhance-Diversity': 'Enhance-Diversity',
   'Graduation-Cap': 'Graduation-Cap',
   Graph: 'Graph',
   Growth: 'Growth',
   Institution: 'Institution',
   'Lightbulb-Idea': 'Lightbulb-Idea',
   Location: 'Location',
   News: 'News',
   Notes: 'Notes',
   People: 'People',
   Person: 'Person',
   'Person-Star': 'Person-Star',
   Phone: 'Phone',
   Ruler: 'Ruler',
   'DPC-Tree': 'DPC-Tree',
   'BUILD-Orange-Branch': 'BUILD-Orange-Branch',
   'BUILD-Orange-Leaf-Gradient': 'BUILD-Orange-Leaf-Gradient',
   'BUILD-Orange-Leaf-Outline': 'BUILD-Orange-Leaf-Outline',
   'BUILD-Orange-Leaf': 'BUILD-Orange-Leaf',
   'BUILD-Orange-Leaves-Gradient': 'BUILD-Orange-Leaves-Gradient',
   'BUILD-Orange-Leaves-Outline': 'BUILD-Orange-Leaves-Outline',
   'BUILD-Orange-Leaves': 'BUILD-Orange-Leaves',
   'CEC-Blue-Branch': 'CEC-Blue-Branch',
   'CEC-Blue-Leaf-Gradient': 'CEC-Blue-Leaf-Gradient',
   'CEC-Blue-Leaf-Outline': 'CEC-Blue-Leaf-Outline',
   'CEC-Blue-Leaf': 'CEC-Blue-Leaf',
   'CEC-Blue-Leaves-Gradient': 'CEC-Blue-Leaves-Gradient',
   'CEC-Blue-Leaves-Outline': 'CEC-Blue-Leaves-Outline',
   'CEC-Blue-Leaves': 'CEC-Blue-Leaves',
   'NIH-Green-Branch': 'NIH-Green-Branch',
   'NIH-Green-Leaf-Gradient': 'NIH-Green-Leaf-Gradient',
   'NIH-Green-Leaf-Outline': 'NIH-Green-Leaf-Outline',
   'NIH-Green-Leaf': 'NIH-Green-Leaf',
   'NIH-Green-Leaves-Gradient': 'NIH-Green-Leaves-Gradient',
   'NIH-Green-Leaves-Outline': 'NIH-Green-Leaves-Outline',
   'NIH-Green-Leaves': 'NIH-Green-Leaves',
   'NRMN-Yellow-Branch': 'NRMN-Yellow-Branch',
   'NRMN-Yellow-Leaf-Gradient': 'NRMN-Yellow-Leaf-Gradient',
   'NRMN-Yellow-Leaf-Outline': 'NRMN-Yellow-Leaf-Outline',
   'NRMN-Yellow-Leaf': 'NRMN-Yellow-Leaf',
   'NRMN-Yellow-Leaves-Gradient': 'NRMN-Yellow-Leaves-Gradient',
   'NRMN-Yellow-Leaves-Outline': 'NRMN-Yellow-Leaves-Outline',
   'NRMN-Yellow-Leaves': 'NRMN-Yellow-Leaves',
};
